name: loading_bloc_builder
description: A special BlocBuilder for displaying the lifecycle of a state with a LoadingStatus.
version: 0.0.1-dev.1
repository: https://github.com/mtwichel/loading-bloc-builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0

dev_dependencies:
  bloc_test: ^8.1.0
  equatable: ^2.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0