name: loading_bloc_builder
description: A special BlocBuilder for displaying the lifecycle of a state with a LoadingStatus.
version: 0.0.1
repository: https://github.com/mtwichel/loading-bloc-builder

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ">=8.0.0 <10.0.0"

dev_dependencies:
  bloc_test: ">=9.0.0 <11.0.0"
  equatable: ^2.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
